name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdfx: ^2.9.2
  google_generative_ai: ^0.4.7
  supabase_flutter: ^2.10.3
  provider: ^6.1.2
  flutter_treeview: ^1.0.7
  json_annotation: ^4.9.0
  http: ^1.2.2
  openai_dart: ^0.6.0
  chat_gpt_sdk: ^3.1.5
  file_picker: ^10.3.7

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true